server:
  port: 9090
spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      default-filters:
        - GatewayLogFilter
      routes:

        - id: vehicle-search-service
          uri: http://localhost:9091
          predicates:
            - Path=/vehicle/search
            - Method=GET
          filters:
            - RewritePath=/vehicle/search, /vehicle

        - id: customer-registration-service
          uri: http://localhost:9092
          predicates:
            - Path=/customer
            - Method=POST